// Catálogo de peças por subcoleção para desmanche
// Cada subcoleção tem ícone, ID de categoria e lista de peças padrão
// As peças são cruzadas com o masterParts do Firestore pelo categoryId

export const SUBCOLLECTIONS = [
  {
    id: "motor_cambio",
    label: "Motor e Câmbio",
    icon: "⚙️",
    categoryIds: ["cat_velas_ignicao", "cat_filtros_oleo", "cat_bombas_combustivel", "cat_filtros_combustivel", "cat_sensores", "cat_correias_dentadas", "cat_injetores", "cat_juntas"],
    parts: [
      { name: "Motor completo", oemRef: "MOTOR_COMPLETO" },
      { name: "Câmbio automático", oemRef: "CAMBIO_AUTO" },
      { name: "Câmbio manual", oemRef: "CAMBIO_MANUAL" },
      { name: "Cabeçote", oemRef: "CABECOTE" },
      { name: "Bloco do motor", oemRef: "BLOCO_MOTOR" },
      { name: "Carter de óleo", oemRef: "CARTER_OLEO" },
      { name: "Alternador", oemRef: "ALTERNADOR" },
      { name: "Compressor A/C", oemRef: "COMPRESSOR_AC" },
      { name: "Bomba d'água", oemRef: "BOMBA_DAGUA" },
      { name: "Turbina", oemRef: "TURBINA" },
      { name: "Intercooler", oemRef: "INTERCOOLER" },
      { name: "Radiador de água", oemRef: "RADIADOR_AGUA" },
      { name: "Correia dentada kit", oemRef: "KIT_CORREIA" },
      { name: "Bomba de óleo", oemRef: "BOMBA_OLEO" },
      { name: "Injetor combustível", oemRef: "INJETOR" },
      { name: "Bomba de combustível", oemRef: "BOMBA_COMB" },
      { name: "Módulo de injeção ECU", oemRef: "ECU_INJECAO" },
      { name: "Sensor de rotação (CKP)", oemRef: "SENSOR_CKP" },
      { name: "Sensor de fase (CMP)", oemRef: "SENSOR_CMP" },
      { name: "Sensor de temperatura motor", oemRef: "SENSOR_TEMP" },
      { name: "Válvula EGR", oemRef: "VALVULA_EGR" },
      { name: "Válvula borboleta", oemRef: "VALVULA_BORB" },
      { name: "Coletor de admissão", oemRef: "COLETOR_ADM" },
      { name: "Coletor de escapamento", oemRef: "COLETOR_ESC" },
    ],
  },
  {
    id: "suspensao_direcao",
    label: "Suspensão e Direção",
    icon: "🔩",
    categoryIds: ["cat_amortecedores", "cat_suspensao_direcao", "cat_rolamentos"],
    parts: [
      { name: "Amortecedor dianteiro direito", oemRef: "AMOR_DD" },
      { name: "Amortecedor dianteiro esquerdo", oemRef: "AMOR_DE" },
      { name: "Amortecedor traseiro direito", oemRef: "AMOR_TD" },
      { name: "Amortecedor traseiro esquerdo", oemRef: "AMOR_TE" },
      { name: "Mola dianteira direita", oemRef: "MOLA_DD" },
      { name: "Mola dianteira esquerda", oemRef: "MOLA_DE" },
      { name: "Mola traseira direita", oemRef: "MOLA_TD" },
      { name: "Mola traseira esquerda", oemRef: "MOLA_TE" },
      { name: "Bandeja inferior direita", oemRef: "BANDEJA_DD" },
      { name: "Bandeja inferior esquerda", oemRef: "BANDEJA_DE" },
      { name: "Cubo de roda dianteiro", oemRef: "CUBO_D" },
      { name: "Cubo de roda traseiro", oemRef: "CUBO_T" },
      { name: "Rolamento de roda dianteiro", oemRef: "ROL_D" },
      { name: "Rolamento de roda traseiro", oemRef: "ROL_T" },
      { name: "Barra estabilizadora dianteira", oemRef: "BARRA_EST_D" },
      { name: "Barra estabilizadora traseira", oemRef: "BARRA_EST_T" },
      { name: "Caixa de direção elétrica", oemRef: "CAIXA_DIR" },
      { name: "Coluna de direção", oemRef: "COLUNA_DIR" },
      { name: "Bomba de direção hidráulica", oemRef: "BOMBA_DIR" },
      { name: "Terminal de direção direito", oemRef: "TERM_DD" },
      { name: "Terminal de direção esquerdo", oemRef: "TERM_DE" },
    ],
  },
  {
    id: "freios",
    label: "Freios",
    icon: "🛑",
    categoryIds: ["cat_pastilhas_freio", "cat_discos_freio", "cat_sapatas_freio"],
    parts: [
      { name: "Disco de freio dianteiro direito", oemRef: "DISCO_DD" },
      { name: "Disco de freio dianteiro esquerdo", oemRef: "DISCO_DE" },
      { name: "Disco de freio traseiro direito", oemRef: "DISCO_TD" },
      { name: "Disco de freio traseiro esquerdo", oemRef: "DISCO_TE" },
      { name: "Pastilha de freio dianteira", oemRef: "PAST_D" },
      { name: "Pastilha de freio traseira", oemRef: "PAST_T" },
      { name: "Sapata de freio traseira", oemRef: "SAPATA_T" },
      { name: "Cilindro mestre de freio", oemRef: "CIL_MESTRE" },
      { name: "Servo freio", oemRef: "SERVO_FREIO" },
      { name: "Pinça de freio dianteira direita", oemRef: "PINCA_DD" },
      { name: "Pinça de freio dianteira esquerda", oemRef: "PINCA_DE" },
      { name: "Pinça de freio traseira direita", oemRef: "PINCA_TD" },
      { name: "Pinça de freio traseira esquerda", oemRef: "PINCA_TE" },
      { name: "Módulo ABS", oemRef: "MODULO_ABS" },
      { name: "Sensor ABS dianteiro direito", oemRef: "ABS_DD" },
      { name: "Sensor ABS dianteiro esquerdo", oemRef: "ABS_DE" },
      { name: "Sensor ABS traseiro direito", oemRef: "ABS_TD" },
      { name: "Sensor ABS traseiro esquerdo", oemRef: "ABS_TE" },
    ],
  },
  {
    id: "eletrica",
    label: "Elétrica e Eletrônica",
    icon: "⚡",
    categoryIds: ["cat_sensores"],
    parts: [
      { name: "Central multimídia / rádio", oemRef: "MULTIMIDIA" },
      { name: "Painel de instrumentos", oemRef: "PAINEL_INST" },
      { name: "Módulo do airbag", oemRef: "MODULO_AIRBAG" },
      { name: "Airbag motorista", oemRef: "AIRBAG_MOT" },
      { name: "Airbag passageiro", oemRef: "AIRBAG_PAS" },
      { name: "Módulo de conforto BCM", oemRef: "BCM" },
      { name: "Central de alarme", oemRef: "ALARME" },
      { name: "Motor do limpador dianteiro", oemRef: "MOTOR_LIMP_D" },
      { name: "Motor do limpador traseiro", oemRef: "MOTOR_LIMP_T" },
      { name: "Motor do vidro elétrico DD", oemRef: "MOT_VID_DD" },
      { name: "Motor do vidro elétrico DE", oemRef: "MOT_VID_DE" },
      { name: "Motor do vidro elétrico TD", oemRef: "MOT_VID_TD" },
      { name: "Motor do vidro elétrico TE", oemRef: "MOT_VID_TE" },
      { name: "Interruptor vidro dianteiro", oemRef: "INT_VID_D" },
      { name: "Farol dianteiro direito", oemRef: "FAROL_DD" },
      { name: "Farol dianteiro esquerdo", oemRef: "FAROL_DE" },
      { name: "Farol traseiro direito", oemRef: "LANTERNA_DD" },
      { name: "Farol traseiro esquerdo", oemRef: "LANTERNA_DE" },
      { name: "Conjunto de chave de seta", oemRef: "CHAVE_SETA" },
      { name: "Caixa de fusíveis", oemRef: "CAIXA_FUS" },
      { name: "Motor de partida", oemRef: "MOTOR_PARTIDA" },
      { name: "Alternador", oemRef: "ALTERNADOR" },
      { name: "Bateria", oemRef: "BATERIA" },
    ],
  },
  {
    id: "escapamento",
    label: "Escapamento",
    icon: "💨",
    categoryIds: [],
    parts: [
      { name: "Catalisador", oemRef: "CATALISADOR" },
      { name: "Coletor de escapamento", oemRef: "COLETOR_ESC" },
      { name: "Silencioso intermediário", oemRef: "SILENC_INT" },
      { name: "Silencioso traseiro", oemRef: "SILENC_T" },
      { name: "Tubo intermediário", oemRef: "TUBO_INT" },
      { name: "Sensor lambda (O2) dianteiro", oemRef: "LAMBDA_D" },
      { name: "Sensor lambda (O2) traseiro", oemRef: "LAMBDA_T" },
      { name: "Flex pipe / tubo flexível", oemRef: "FLEX_PIPE" },
      { name: "Suporte de escapamento", oemRef: "SUP_ESC" },
    ],
  },
  {
    id: "lataria_vidros",
    label: "Lataria e Vidros",
    icon: "🚗",
    categoryIds: [],
    parts: [
      { name: "Capô", oemRef: "CAPO" },
      { name: "Para-choque dianteiro", oemRef: "PARACHOQUE_D" },
      { name: "Para-choque traseiro", oemRef: "PARACHOQUE_T" },
      { name: "Porta dianteira direita", oemRef: "PORTA_DD" },
      { name: "Porta dianteira esquerda", oemRef: "PORTA_DE" },
      { name: "Porta traseira direita", oemRef: "PORTA_TD" },
      { name: "Porta traseira esquerda", oemRef: "PORTA_TE" },
      { name: "Tampa do porta-malas", oemRef: "TAMPA_MALAS" },
      { name: "Paralama dianteiro direito", oemRef: "PARALAMA_DD" },
      { name: "Paralama dianteiro esquerdo", oemRef: "PARALAMA_DE" },
      { name: "Vidro dianteiro (parabrisa)", oemRef: "PARABRISA" },
      { name: "Vidro traseiro", oemRef: "VIDRO_T" },
      { name: "Vidro lateral direito", oemRef: "VIDRO_LD" },
      { name: "Vidro lateral esquerdo", oemRef: "VIDRO_LE" },
      { name: "Espelho retrovisor direito", oemRef: "ESP_DD" },
      { name: "Espelho retrovisor esquerdo", oemRef: "ESP_DE" },
      { name: "Espelho retrovisor interno", oemRef: "ESP_INT" },
    ],
  },
  {
    id: "interior",
    label: "Interior e Acabamento",
    icon: "🪑",
    categoryIds: [],
    parts: [
      { name: "Banco dianteiro direito", oemRef: "BANCO_DD" },
      { name: "Banco dianteiro esquerdo", oemRef: "BANCO_DE" },
      { name: "Banco traseiro", oemRef: "BANCO_T" },
      { name: "Volante", oemRef: "VOLANTE" },
      { name: "Console central", oemRef: "CONSOLE" },
      { name: "Tapete original", oemRef: "TAPETE" },
      { name: "Revestimento de porta DD", oemRef: "REV_PORTA_DD" },
      { name: "Revestimento de porta DE", oemRef: "REV_PORTA_DE" },
      { name: "Revestimento de porta TD", oemRef: "REV_PORTA_TD" },
      { name: "Revestimento de porta TE", oemRef: "REV_PORTA_TE" },
      { name: "Ar condicionado compressor", oemRef: "COMPRESSOR_AC" },
      { name: "Evaporador A/C", oemRef: "EVAPORADOR" },
      { name: "Caixa de ventilação", oemRef: "CAIXA_VENT" },
    ],
  },
  {
    id: "rodas_pneus",
    label: "Rodas e Pneus",
    icon: "🛞",
    categoryIds: [],
    parts: [
      { name: "Roda liga leve DD", oemRef: "RODA_DD" },
      { name: "Roda liga leve DE", oemRef: "RODA_DE" },
      { name: "Roda liga leve TD", oemRef: "RODA_TD" },
      { name: "Roda liga leve TE", oemRef: "RODA_TE" },
      { name: "Pneu dianteiro direito", oemRef: "PNEU_DD" },
      { name: "Pneu dianteiro esquerdo", oemRef: "PNEU_DE" },
      { name: "Pneu traseiro direito", oemRef: "PNEU_TD" },
      { name: "Pneu traseiro esquerdo", oemRef: "PNEU_TE" },
      { name: "Estepe completo", oemRef: "ESTEPE" },
      { name: "Calota jogo completo", oemRef: "CALOTA" },
    ],
  },
];

// Subcoleções selecionadas por padrão (conforme especificação do usuário)
export const DEFAULT_SELECTED = ["freios", "eletrica", "escapamento"];
